#!/usr/bin/env python3
import os
from colorama import *
print(Fore.GREEN, "[+] Installing This Will Take A While ...")
os.system("mkdir ~/PMATools && cd ~/PMATools/")
os.system("apt update")
os.system("apt install vim nano neofetch apktool nmap ruby bundler wget curl perl git python3-pip python3-wheel -y")
os.system("apt install gcc g++ xterm hydra xhydra ettercap-text-only wireshark libpcap libusb tshark net-tools libpcap libnet make apache2 tor nginx-y")
print(Fore.GREEN, "[+] Installing Netdiscover ...")
os.system("git clone https://github.com/netdiscover-scanner/netdiscover.git")
print(Fore.GREEN, "[+] Installing Airgeddon ...")
os.system("git clone https://github.com/v1s1t0r1sh3r3/airgeddon.git")
print(Fore.GREEN, "[+] Installing Bettercap ...")
os.system("git clone https://github.com/bettercap/bettercap.git")
os.system("apt install iw aircrack-ng iproute2 procps procps-ng libssl-dev libnl-dev awk pciutils crunch mdk4 hostapd lighttpd iptables  -y")
os.system("apt install hcxdumptool hostapd ettercap-graphical isc-dhcp-server dnsmasq reaver bully openssl pixiewps hcxtools -y")
os.system("curl -sSL https://get.rvm.io | bash -s -- --autolibs=install-packages")
print(Fore.GREEN, "[+] Installing Beef-XSS ...")
os.system(".rvm/bin/rvm requirements")
os.system("curl -sSL https://get.rvm.io | bash -s stable --ruby")
os.system('rvm install "ruby-2.5.3"')
os.system("git clone https://github.com/beefproject/beef.git && ./beef/install")
print(Fore.GREEN, "[+] Installing Exploit-DB ...")
os.system("git clone https://github.com/offensive-security/exploitdb.git /opt/exploitdb")
os.system("ln -sf /opt/exploitdb/searchsploit /usr/local/bin/searchsploit")
print(Fore.GREEN, "[+] Installing Maltego ...")
os.system("wget https://maltego-downloads.s3.us-east-2.amazonaws.com/linux/Maltego.v4.2.19.13940.deb && apt install ./Maltego.v4.2.19.13940.deb -y")
os.system("apt install metasploit-framework openjdk-11-jre openjdk-11-jdk -y")
print(Fore.GREEN, "[+] Installing Responder ...")
os.system("git clone https://github.com/SpiderLabs/Responder.git")
os.system("python3 -m pip install poetry")
print(Fore.GREEN, "[+] Installing Powershell-Empire ...")
os.system("git clone --recursive https://github.com/BC-SECURITY/Empire.git && ./Empire/setup/install.sh && poetry install")
print(Fore.GREEN, "[+] Installing Anonsurf ...")
os.system("git clone https://github.com/Und3rf10w/kali-anonsurf.git && chmod +x kali-anonsurf/installer.sh && ./kali-anonsurf/installer.sh")

